### ISSUE TITLE
Nginx 1.18.0

### ISSUE THREAD

**Issue by everanium** [ip2location/ip2proxy-nginx#10]
Hello, can`t compile nginx 1.18.0 with ip2proxy module.

Upd: 1.16.1 too can`t compile :(

Error:

```rong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/mail -I src/stream \
        -o objs/addon/ip2mod-proxy/ngx_http_ip2proxy.o \
        /root/compile/ip2mod-proxy/ngx_http_ip2proxy.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fdebug-prefix-map=/root/compile/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs \
        -o objs/ngx_modules.o \
        objs/ngx_modules.c
/root/compile/ip2mod-proxy/ngx_http_ip2proxy.c: In function ‘ngx_http_ip2proxy_exit_process’:
/root/compile/ip2mod-proxy/ngx_http_ip2proxy.c:301:4: error: implicit declaration of function ‘IP2Proxy_DB_del_shm’ [-Werror=implicit-function-declaration]
    IP2Proxy_DB_del_shm();
    ^~~~~~~~~~~~~~~~~~~
sed -e "s|%%PREFIX%%|/etc/nginx|" \
        -e "s|%%PID_PATH%%|/var/run/nginx.pid|" \
        -e "s|%%CONF_PATH%%|/etc/nginx/nginx.conf|" \
        -e "s|%%ERROR_LOG_PATH%%|/var/log/nginx/error.log|" \
        < man/nginx.8 > objs/nginx.8
cc1: all warnings being treated as errors
objs/Makefile:1827: recipe for target 'objs/addon/ip2mod-proxy/ngx_http_ip2proxy.o' failed
make[2]: *** [objs/addon/ip2mod-proxy/ngx_http_ip2proxy.o] Error 1
make[2]: Leaving directory '/root/compile/nginx-1.18.0/debian/build-nginx'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/root/compile/nginx-1.18.0/debian/build-nginx'
debian/rules:50: recipe for target 'build-arch.nginx' failed
make: *** [build-arch.nginx] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

CFLAGS:

```CFLAGS="" ./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --add-module=/root/compile/ip2mod-location --add-module=/root/compile/ip2mod-proxy --with-cc-opt="-g -O2 -fdebug-prefix-map=/root/compile/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC" --with-ld-opt="-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie"```

GCC Version:

```root@mm-eu:~/compile# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)```

**Comment by pingvinton** [comment]
Hi, I have the same issues. I try patch module with this code:
`--- ngx_http_ip2proxy.c.orig    2020-10-14 12:48:14.853077039 +0200
+++ ngx_http_ip2proxy.c 2020-10-14 12:47:00.422464857 +0200
@@ -298,7 +298,7 @@
                IP2Proxy_close(cfg->database);

                if (cfg->access_type == IP2PROXY_SHARED_MEMORY) {
-                       IP2Proxy_DB_del_shm();
+                       IP2Proxy_delete_shm();
                }

                cfg->database = NULL;
@@ -332,7 +332,7 @@
                IP2Proxy_close(clean_ctx->main_cf->database);

                if (clean_ctx->main_cf->access_type == IP2PROXY_SHARED_MEMORY) {
-                       IP2Proxy_DB_del_shm();
+                       IP2Proxy_delete_shm();
                }

                ngx_log_debug0(NGX_LOG_DEBUG_HTTP, clean_ctx->cycle->log, 0,`

**Comment by pingvinton** [comment]
My patch is there
https://github.com/pingvinton/nginx-ip2proxy-nginx

**Comment by everanium** [comment]
Thank You, later I try to build with patch :)

> My patch is there
> https://github.com/pingvinton/nginx-ip2proxy-nginx

Thank You 👍

**Comment by ip2location-com** [comment]
Please compile with the latest commit.

**Comment by everanium** [comment]
Successful compiled from master branch. Working OK. Thank You.
