### ISSUE TITLE
config ip2proxy_access_type shared_memory/cache_memory seems not work

### ISSUE THREAD

**Issue by angus-ssl** [ip2location/ip2proxy-nginx#12]
Hi @ip2location ,

The setting of "ip2proxy_access_type shared_memory/cache_memory" in nginx.conf seems loading fail, and saw it go back to file_io.
Therefore, it cause cpu loading up to 100%, but did not show any error message.
```
ngx_http_ip2proxy.c:356
    IP2Proxy_open_mem(gcf->handler, gcf->access_type);
```
Kindly help me to check this issue. Thanks a lot.

**Comment by ip2location-com** [comment]
Please use the latest commit and remove "ip2proxy_access_type" from your config file.
