### ISSUE TITLE
reload nginx the process cpu up to 100%

### ISSUE THREAD

**Issue by angus-ssl** [ip2location/ip2proxy-nginx#13]
Hi @ip2location ,
I have met some issue.
I use the lastest commit and did not used the ip2proxy_access_type.

Test setting:
```
nginx >> worker_processes 1;
initial >> work fine
reload multi times>> work fine
```
```
nginx >> worker_processes 8;
initial >> work fine
reload one time >> 1 of 8 process up to 100%
reload second time >> 2 of 8 process up to 100%
```

The process which cpu up to 100% seems goes to file_io, in this situation, the proxy_Type can not get value.
Didn't know if this situation is database info didn't write in memory.
Please help to check, thank you.

**Comment by angus-ssl** [comment]
Hello sir, have any update?

**Comment by ip2location-com** [comment]
Will look into this.

**Comment by ip2location-com** [comment]
Kindly try it again with the latest version.
