### ISSUE TITLE
Error with configuration

### ISSUE THREAD

**Issue by kevin25** [ip2location/ip2proxy-nginx#14]
I compiled it successfully. However, when I added it to the nginx. I got the error.

ip2proxy on;
ip2proxy_database /etc/ip2proxy/IP2PROXY-LITE-PX10.BIN;
ip2proxy_reverse_proxy on;
ip2proxy_access_type shared_memory;

nginx: [emerg] unknown directive "ip2proxy" in /etc/nginx/nginx.conf:20

**Comment by kevin25** [comment]
When i compiled it as the module, i got this 

/opt/nginx/sbin/nginx: error while loading shared libraries: libIP2Proxy.so.2: cannot open shared object file: No such file or directory

nginx 1.18.0

**Comment by ip2location-com** [comment]
Please run the command:

`ldconfig /usr/local/lib`
