### ISSUE TITLE
Source ip from GET parameter

### ISSUE THREAD

**Issue by Lenon832** [ip2location/ip2proxy-nginx#19]
it is necessary that the module determines the proxy not from the IP of the real source (remote addr or x-forwarder-for), but from the GET parameter ip (enable to configure in the config)

**Comment by Lenon832** [comment]
And i am using these variables from PX2 database 
ip2proxy_database  /usr/share/PX2-IP-PROXYTYPE-COUNTRY.BIN;

proxy_set_header X-ip2l-country $ip2proxy_country_short;
proxy_set_header X-ip2l-is-proxy $ip2proxy_is_proxy;
proxy_set_header X-ip2l-proxy-type $ip2proxy_proxy_type;

and on backend i got these 

'HTTP_X_IP2L_PROXY_TYPE' => 'FR',
'HTTP_X_IP2L_IS_PROXY' => '1',
'HTTP_X_IP2L_COUNTRY' => 'FR',
'HTTP_X_FORWARDED_FOR' => '92.204.164.167',

HTTP_X_IP2L_PROXY_TYPE wrong value. Got country_short

**Comment by ip2location-com** [comment]
Kindly try it again with the latest version.
