### ISSUE TITLE
How do I update DB.BIN

### ISSUE THREAD

**Issue by reid-me** [ip2location/ip2proxy-nginx#2]
What is the best way to update (or replace) a DB.BIN database on nginx?

**Comment by ip2location-com** [comment]
You can use the downloader script from https://www.ip2location.com/free/downloader to replace the .BIN file.

**Comment by fas3r** [comment]
Hello @ip2location ,

Does it require a restart of nginx ? 

If yes, would it be possible to add a method to the module to reload/refresh the file when using `cache_memory` ?

it could be located in the `location` context, something like : 

```
location /refresh_proxy {
   
   ip2proxy_refresh;

}
```

Where `ip2proxy_refresh` would clean the memory and reload the file in memory ? 

Thanks

**Comment by ip2location-com** [comment]
Thanks for your suggestion. I will add this function into our to-do list.

**Comment by fas3r** [comment]
Hello @ip2location ,

Looking forward to it. Do you have an idea when we could expect it to be ready ? 

Thanks again for your prompt answer.

**Comment by fas3r** [comment]
Hello, would not be better to leave this issue open until the task is completed ? 

Thanks
