### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by HmHasan22** [ip2location/ip2proxy-nginx#21]
module "/usr/share/nginx/modules/ngx_http_ip2proxy_module.so" is not binary compatible in /etc/nginx/nginx.conf:5

**Comment by ip2location-com** [comment]
You need to build Nginx and the module with the same build flags. To create a dynamic module for Nginx, it is necessary to compile Nginx with specific flags and include the --add-dynamic-module option. Using a different Nginx binary might result in incorrect functionality of the modules.
