### ISSUE TITLE
Detect the VPS

### ISSUE THREAD

**Issue by kevin25** [ip2location/ip2proxy-nginx#5]
How can I detect the visitors who are using VPN and then return them to error 404?

**Comment by kevin25** [comment]
I bet it is 

> if ( $ip2proxy_is_proxy == "Y") { return 404;}

**Comment by ip2location-com** [comment]
Hi, 

The syntax in Nginx is:

`
if ( $ip2proxy_is_proxy = "Y") {
    return 404;
}
`

Only a single equal sign needed.

**Comment by kevin25** [comment]
Thank you. Is there any way to ignore it from a url like /admin/  ?

**Comment by ip2location-com** [comment]
Since Nginx cannot use multiple conditional if-else, I suggest you try following statements:

`set $display_404 = "";

if ($request_uri = '/admin' ) {
	set $display_404 = "1";
}

if ($ip2proxy_is_proxy = 'Y') {
	set $display_404 "${display_404}1";
}

if ($display_404 = "11") {
	return 404;
}`

**Comment by kevin25** [comment]
Thank you so much. I'll give it a try.
