### ISSUE TITLE
dynamic update of BIN

### ISSUE THREAD

**Issue by fas3r** [ip2location/ip2proxy-nginx#6]
Hello @ip2location ,

In [may 2019](https://github.com/ip2location/ip2proxy-nginx/issues/2) I opened a first issue on this topic, would it be possible to add a method to the module to reload/refresh the file when using cache_memory ?

it could be located in the location context, something like :

location /refresh_proxy {
   
   ip2proxy_refresh;

}

Where ip2proxy_refresh would clean the memory and reload the file in memory.

Is there any ETA for such feature ?

Thanks

**Comment by zi0r** [comment]
A reload of nginx should reload the database.
