### ISSUE TITLE
Segfault when addr.data contains two IP address 

### ISSUE THREAD

**Issue by disc** [ip2location/ip2proxy-nginx#9]
Found a segfault on line `(void) ngx_copy((void *)ip_addr, addr.data, addr.len);` when addr.data contains two IP addresses `2806:103e:21:7021:15e1:2a39:ed91:263b,66.249.80.67`

**Comment by ip2location-com** [comment]
May I know in what situation two IP address appeared in the address?

**Comment by disc** [comment]
> May I know in what situation two IP address appeared in the address?

We use Cloudflare and it sometimes provides two IP addresses in case of IPv6 address.

**Comment by ip2location-com** [comment]
It seems like Nginx are not able to split the comma.

Please follow the instructions provided to do a mapping.

https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

**Comment by disc** [comment]
Solved by disabling this option **ip2proxy_reverse_proxy**, but i belive there should not be a segfault in case when ipaddr longer than buffer.
How about return NGX_ERR and the error message for error_log in this case?

**Comment by ip2location-com** [comment]
We will add this in coming version.
